# Generated by Django 5.2 on 2025-04-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaGo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_clientes/'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_profesionales/'),
        ),
    ]
