# Generated by Django 5.2 on 2025-04-19 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaGo', '0002_clientprofile_foto_professionalprofile_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='experiencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='ConectaGo.professionalprofile')),
            ],
        ),
    ]
