# Generated by Django 5.2 on 2025-04-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaGo', '0003_professionalprofile_experiencia_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
