# Generated by Django 5.2 on 2025-04-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaGo', '0005_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
