# Generated by Django 5.2 on 2025-04-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaGo', '0006_professionalprofile_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='entidad_emisora',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='nombre_certificado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
