# Generated by Django 5.2 on 2025-04-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaGo', '0007_professionalprofile_archivo_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
