# Generated by Django 5.2 on 2025-05-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaGo', '0008_professionalprofile_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='schedule',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
