# Generated by Django 5.2 on 2025-05-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaGo', '0009_professionalprofile_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='calendly_event_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
