# Generated by Django 5.2.1 on 2025-05-16 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaGo', '0010_professionalprofile_calendly_event_uri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField()),
                ('opinion', models.TextField(max_length=500)),
                ('likes', models.JSONField(blank=True, null=True)),
                ('improve', models.JSONField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='ConectaGo.clientprofile')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ConectaGo.professionalprofile')),
            ],
        ),
    ]
