# Generated by Django 5.2.1 on 2025-05-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaGo', '0011_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='lugar',
        ),
    ]
