# Generated by Django 5.2.1 on 2025-05-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaGo', '0012_remove_review_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='rating',
            field=models.FloatField(default=0.0, help_text='Valoración promedio del profesional (0 a 5)'),
        ),
    ]
