# Generated by Django 5.2.1 on 2025-05-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaGo', '0016_appointment_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
