# Generated by Django 5.2.1 on 2025-06-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaGo', '0017_appointment_client_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notification_seen',
            field=models.BooleanField(default=False),
        ),
    ]
