# Generated by Django 5.2.1 on 2025-06-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaGo', '0019_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='certification_rejection_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='certification_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado')], default='pending', max_length=10),
        ),
    ]
