# Generated by Django 5.2.1 on 2025-06-04 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaGo', '0020_chatroom_chatmessage'),
        ('ConectaGo', '0021_notification'),
    ]

    operations = [
    ]
