# Generated by Django 5.2.1 on 2025-06-20 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaGo', '0022_merge_0020_chatroom_chatmessage_0021_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='professional_photos/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ConectaGo.professionalprofile')),
            ],
        ),
    ]
